// ===== Global State =====
let sections = [];
let currentSection = null;
let currentChapter = null;
let currentQuestionIndex = 0;
let userAnswers = {};
let examStartTime = null;
let timerInterval = null;
let currentFilter = 'all';
let searchQuery = '';
let selectedChapters = []; // For multiple chapter selection
let combinedQuestions = []; // Questions from all selected chapters
let examMode = 'single'; // 'single' or 'multiple'

// ===== Initialize App =====
document.addEventListener('DOMContentLoaded', () => {
    loadSections();
    setupEventListeners();
    hljs.highlightAll();
});

// ===== Event Listeners =====
function setupEventListeners() {
    // Search
    document.getElementById('searchInput').addEventListener('input', (e) => {
        searchQuery = e.target.value.toLowerCase();
        filterSections();
    });

    // Filters
    document.querySelectorAll('.filter-btn').forEach(btn => {
        btn.addEventListener('click', (e) => {
            document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
            e.currentTarget.classList.add('active');
            currentFilter = e.currentTarget.dataset.filter;
            filterSections();
        });
    });
}

// ===== Load Sections =====
async function loadSections() {
    try {
        // Auto-generated by Exam Engine Editor
        sections = [
            {
                "id": "java2",
                "title": "Java 2",
                "icon": "🎯",
                "folder": "java2",
                "chapters": [
                    {
                        "id": "chapter9",
                        "title": "Chapter 9 Objects and Classes",
                        "file": "chapter9.json",
                        "questions": 52
                    },
                    {
                        "id": "chapter10",
                        "title": "Chapter 10 Object-Oriented Thinking",
                        "file": "chapter10.json",
                        "questions": 47
                    },
                    {
                        "id": "chapter11",
                        "title": "Chapter 11 Inheritance and Polymorphism",
                        "file": "chapter11.json",
                        "questions": 65
                    },
                    {
                        "id": "chapter12",
                        "title": "Chapter 12 Exception Handling and Text I/O",
                        "file": "chapter12.json",
                        "questions": 48
                    },
                    {
                        "id": "chapter13",
                        "title": "Chapter 13 Abstract Classes and Interfaces",
                        "file": "chapter13.json",
                        "questions": 35
                    },
                    {
                        "id": "chapter17",
                        "title": "Chapter 17 Binary I/O",
                        "file": "chapter17.json",
                        "questions": 20
                    }
                ],
                "totalQuestions": 267,
                "status": "not-started"
            }
        ];

        console.log('✓ Sections loaded:', sections[0].chapters.length, 'chapters,', sections[0].totalQuestions, 'questions');
        renderSections();
        updateFilterCounts();
    } catch (error) {
        console.error('Error loading sections:', error);
    }
}

// ===== Render Sections =====
function renderSections() {
    const grid = document.getElementById('sectionsGrid');
    const noResults = document.getElementById('noResults');

    const filteredSections = sections.filter(section => {
        const matchesSearch = section.title.toLowerCase().includes(searchQuery);
        const matchesFilter = currentFilter === 'all' || section.status === currentFilter;
        return matchesSearch && matchesFilter;
    });

    if (filteredSections.length === 0) {
        grid.style.display = 'none';
        noResults.style.display = 'block';
        return;
    }

    grid.style.display = 'grid';
    noResults.style.display = 'none';

    grid.innerHTML = filteredSections.map(section => `
        <div class="section-card" onclick="openSection('${section.id}')">
            <span class="section-icon">${section.icon}</span>
            <h3 class="section-title">${section.title}</h3>
            <div class="section-meta">
                <div class="meta-item">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"></path>
                        <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"></path>
                    </svg>
                    ${section.chapters.length} Chapter${section.chapters.length !== 1 ? 's' : ''}
                </div>
                <div class="meta-item">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <circle cx="12" cy="12" r="10"></circle>
                        <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>
                        <line x1="12" y1="17" x2="12.01" y2="17"></line>
                    </svg>
                    ${section.totalQuestions} Question${section.totalQuestions !== 1 ? 's' : ''}
                </div>
            </div>
            <span class="section-status status-${section.status}">
                ${section.status.replace('-', ' ').replace(/\b\w/g, l => l.toUpperCase())}
            </span>
        </div>
    `).join('');
}

// ===== Filter Sections =====
function filterSections() {
    renderSections();
}

// ===== Update Filter Counts =====
function updateFilterCounts() {
    document.getElementById('countAll').textContent = sections.length;
    document.getElementById('countCompleted').textContent = sections.filter(s => s.status === 'completed').length;
    document.getElementById('countInProgress').textContent = sections.filter(s => s.status === 'in-progress').length;
    document.getElementById('countNotStarted').textContent = sections.filter(s => s.status === 'not-started').length;
}

// ===== Open Section =====
function openSection(sectionId) {
    currentSection = sections.find(s => s.id === sectionId);
    if (!currentSection) return;

    const modal = document.getElementById('chapterModal');
    const modalTitle = document.getElementById('modalTitle');
    const chaptersList = document.getElementById('chaptersList');

    modalTitle.textContent = `${currentSection.title} - Select Chapter(s)`;

    // Add mode selection
    const modeSelection = `
        <div class="mode-selection" style="margin-bottom: 20px; padding: 15px; background: #f5f5f5; border-radius: 8px;">
            <h4 style="margin: 0 0 10px 0; font-size: 14px; font-weight: 600;">Exam Mode:</h4>
            <label style="display: flex; align-items: center; margin: 8px 0; cursor: pointer;">
                <input type="radio" name="examMode" value="single" checked onchange="setExamMode('single')" style="margin-right: 10px;">
                <span><strong>Single Chapter</strong> - One chapter at a time</span>
            </label>
            <label style="display: flex; align-items: center; margin: 8px 0; cursor: pointer;">
                <input type="radio" name="examMode" value="multiple" onchange="setExamMode('multiple')" style="margin-right: 10px;">
                <span><strong>Multiple Chapters</strong> - Select multiple chapters</span>
            </label>
        </div>
    `;

    chaptersList.innerHTML = modeSelection + `
        <div id="chaptersContainer">
            ${examMode === 'single' ? renderSingleChapters() : renderMultipleChapters()}
        </div>
    `;

    modal.classList.add('active');
}

// ===== Set Exam Mode =====
function setExamMode(mode) {
    examMode = mode;
    selectedChapters = [];
    document.getElementById('chaptersContainer').innerHTML =
        mode === 'single' ? renderSingleChapters() : renderMultipleChapters();
}

// ===== Render Single Chapters =====
function renderSingleChapters() {
    return currentSection.chapters.map(chapter => `
        <div class="chapter-item" onclick="startChapter('${chapter.id}')">
            <div class="chapter-info">
                <h3>${chapter.title}</h3>
                <p>${chapter.questions} questions</p>
            </div>
            <div class="chapter-arrow">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <polyline points="9 18 15 12 9 6"></polyline>
                </svg>
            </div>
        </div>
    `).join('');
}

// ===== Render Multiple Chapters =====
function renderMultipleChapters() {
    return `
        <div class="chapters-selection">
            ${currentSection.chapters.map(chapter => `
                <label class="chapter-checkbox-item" style="display: flex; align-items: center; padding: 12px; margin: 8px 0; border: 2px solid #e0e0e0; border-radius: 8px; cursor: pointer; transition: all 0.2s;">
                    <input 
                        type="checkbox" 
                        value="${chapter.id}"
                        data-questions="${chapter.questions}"
                        onchange="toggleChapterSelection('${chapter.id}', this.checked, ${chapter.questions})"
                        style="margin-right: 12px; cursor: pointer; width: 18px; height: 18px;"
                    />
                    <div style="flex: 1;">
                        <h3 style="margin: 0; font-size: 14px; font-weight: 600;">${chapter.title}</h3>
                        <p style="margin: 4px 0 0 0; font-size: 13px; color: #666;">${chapter.questions} questions</p>
                    </div>
                </label>
            `).join('')}
            ${selectedChapters.length > 0 ? `
                <div style="margin-top: 20px; padding: 15px; background: #e8f5e9; border-radius: 8px; border-left: 4px solid #4caf50;">
                    <div style="font-size: 14px; margin-bottom: 10px;">
                        <strong>Selected:</strong> ${selectedChapters.length} chapter(s) - 
                        <span id="totalQuestionsCount">0</span> total questions
                    </div>
                    <button onclick="startMultipleChapters()" style="
                        width: 100%;
                        padding: 10px;
                        background: #4caf50;
                        color: white;
                        border: none;
                        border-radius: 6px;
                        cursor: pointer;
                        font-weight: 600;
                        font-size: 14px;
                    ">
                        Start Exam
                    </button>
                </div>
            ` : ''}
        </div>
    `;
}

// ===== Toggle Chapter Selection =====
function toggleChapterSelection(chapterId, isChecked, questionCount) {
    if (isChecked) {
        if (!selectedChapters.includes(chapterId)) {
            selectedChapters.push(chapterId);
        }
    } else {
        selectedChapters = selectedChapters.filter(id => id !== chapterId);
    }

    updateMultiChapterUI();
}

// ===== Update Multi-Chapter UI =====
function updateMultiChapterUI() {
    const totalQuestions = selectedChapters.reduce((sum, chapterId) => {
        const chapter = currentSection.chapters.find(c => c.id === chapterId);
        return sum + (chapter ? chapter.questions : 0);
    }, 0);

    const countElement = document.getElementById('totalQuestionsCount');
    if (countElement) {
        countElement.textContent = totalQuestions;
    }
}

// ===== Close Chapter Modal =====
function closeChapterModal() {
    document.getElementById('chapterModal').classList.remove('active');
}

// ===== Start Chapter (Single) =====
async function startChapter(chapterId) {
    const chapter = currentSection.chapters.find(c => c.id === chapterId);
    if (!chapter) return;

    try {
        const response = await fetch(`data/${currentSection.folder}/${chapter.file}`);
        const data = await response.json();

        // Handle both array and object formats
        currentChapter = Array.isArray(data) ? data[0] : data;

        // Ensure questions array exists
        if (!currentChapter.questions || !Array.isArray(currentChapter.questions)) {
            throw new Error('Invalid chapter data: missing questions array');
        }

        // Single chapter mode
        examMode = 'single';
        combinedQuestions = currentChapter.questions;
        currentQuestionIndex = 0;
        userAnswers = {};
        examStartTime = Date.now();

        closeChapterModal();
        showPage('examPage');
        startTimer();
        renderQuestion();
    } catch (error) {
        console.error('Error loading chapter:', error);
        alert('Failed to load chapter: ' + error.message);
    }
}

// ===== Start Multiple Chapters =====
async function startMultipleChapters() {
    if (selectedChapters.length === 0) {
        alert('Please select at least one chapter');
        return;
    }

    try {
        combinedQuestions = [];
        let chapterData = [];

        // Load all selected chapters
        for (const chapterId of selectedChapters) {
            const chapter = currentSection.chapters.find(c => c.id === chapterId);
            if (!chapter) continue;

            const response = await fetch(`data/${currentSection.folder}/${chapter.file}`);
            const data = await response.json();

            const chapterContent = Array.isArray(data) ? data[0] : data;

            if (chapterContent.questions && Array.isArray(chapterContent.questions)) {
                // Add chapter info to questions
                chapterContent.questions.forEach(q => {
                    q.chapterId = chapterId;
                    q.chapterTitle = chapter.title;
                });
                combinedQuestions = combinedQuestions.concat(chapterContent.questions);
                chapterData.push({ id: chapterId, title: chapter.title });
            }
        }

        if (combinedQuestions.length === 0) {
            throw new Error('No questions found in selected chapters');
        }

        // Set up combined exam
        examMode = 'multiple';
        currentChapter = {
            title: `Multiple Chapters (${selectedChapters.length})`,
            questions: combinedQuestions,
            isMultiChapter: true,
            chapters: chapterData
        };

        currentQuestionIndex = 0;
        userAnswers = {};
        examStartTime = Date.now();

        closeChapterModal();
        showPage('examPage');
        startTimer();
        renderQuestion();
    } catch (error) {
        console.error('Error loading chapters:', error);
        alert('Failed to load chapters: ' + error.message);
    }
}

// ===== Show Page =====
function showPage(pageId) {
    document.querySelectorAll('.page').forEach(page => page.classList.remove('active'));
    document.getElementById(pageId).classList.add('active');
}

// ===== Start Timer =====
function startTimer() {
    if (timerInterval) clearInterval(timerInterval);

    timerInterval = setInterval(() => {
        const elapsed = Date.now() - examStartTime;
        const minutes = Math.floor(elapsed / 60000);
        const seconds = Math.floor((elapsed % 60000) / 1000);
        document.getElementById('timerText').textContent =
            `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
    }, 1000);
}

// ===== Render Question =====
function renderQuestion() {
    const question = currentChapter.questions[currentQuestionIndex];
    const container = document.getElementById('questionContainer');

    // Set title with chapter info for multi-chapter mode
    if (currentChapter.isMultiChapter && question.chapterTitle) {
        document.getElementById('examTitle').textContent = `${question.chapterTitle}`;
    } else {
        document.getElementById('examTitle').textContent = currentChapter.title;
    }

    document.getElementById('progressText').textContent =
        `${currentQuestionIndex + 1}/${currentChapter.questions.length}`;

    const progress = ((currentQuestionIndex + 1) / currentChapter.questions.length) * 100;
    document.getElementById('progressBar').style.width = `${progress}%`;

    const isMultipleChoice = question.inputType === 'checkbox';
    const savedAnswer = userAnswers[question.id] || (isMultipleChoice ? [] : '');
    const answerStatus = window.answerStatus || {}; // Track answer check status

    // Build question header with chapter tag for multi-chapter
    let headerHtml = `<div class="question-number">Question ${currentQuestionIndex + 1} of ${currentChapter.questions.length}`;
    if (currentChapter.isMultiChapter && question.chapterTitle) {
        headerHtml += ` <span style="background: #e3f2fd; color: #1976d2; padding: 2px 8px; border-radius: 4px; font-size: 12px; margin-left: 10px; font-weight: 500;">${question.chapterTitle}</span>`;
    }
    headerHtml += `</div>`;

    container.innerHTML = headerHtml + `
        <div class="question-text">${question.text}</div>
        <div class="choices">
            ${question.choices.map(choice => {
        const isChecked = isMultipleChoice
            ? savedAnswer.includes(choice.value)
            : savedAnswer === choice.value;

        return `
                    <label class="choice ${isChecked ? 'selected' : ''}" for="choice-${choice.value}">
                        <input 
                            type="${question.inputType}" 
                            id="choice-${choice.value}"
                            name="${question.inputName}" 
                            value="${choice.value}"
                            ${isChecked ? 'checked' : ''}
                            onchange="handleAnswerChange('${question.id}', '${choice.value}', ${isMultipleChoice})"
                        />
                        <span class="choice-label">
                            <strong>${choice.label}.</strong> ${choice.text}
                        </span>
                    </label>
                `;
    }).join('')}
        </div>
        
        ${savedAnswer ? `
            <div class="answer-check-section">
                <button class="check-answer-btn" onclick="checkAnswer('${question.id}')">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                    </svg>
                    Check Answer
                </button>
                ${answerStatus[question.id] ? `
                    <div class="answer-feedback ${answerStatus[question.id].isCorrect ? 'correct' : 'incorrect'}">
                        <span class="feedback-icon">${answerStatus[question.id].isCorrect ? '✓' : '✗'}</span>
                        <span class="feedback-text">
                            ${answerStatus[question.id].isCorrect ? 'Correct!' : 'Incorrect. Correct answer: ' + answerStatus[question.id].correctAnswer}
                        </span>
                    </div>
                ` : ''}
            </div>
        ` : ''}
    `;

    // Highlight code blocks
    container.querySelectorAll('pre code').forEach((block) => {
        hljs.highlightElement(block);
    });

    // Update navigation buttons
    document.getElementById('prevBtn').disabled = currentQuestionIndex === 0;

    const isLastQuestion = currentQuestionIndex === currentChapter.questions.length - 1;
    document.getElementById('nextBtn').style.display = isLastQuestion ? 'none' : 'flex';
    document.getElementById('submitBtn').style.display = isLastQuestion ? 'flex' : 'none';
}

// ===== Check Answer =====
function checkAnswer(questionId) {
    const question = currentChapter.questions.find(q => q.id === questionId);
    if (!question) return;

    if (!window.answerStatus) {
        window.answerStatus = {};
    }

    const userAnswer = userAnswers[questionId];
    let isCorrect = false;
    let displayCorrectAnswer = question.correctAnswer;

    try {
        // Handle different question types
        if (question.inputType === 'checkbox') {
            // Multiple selection - compare as sorted arrays
            const userAnswerArray = userAnswer || [];
            let correctAnswerArray = question.correctAnswer;

            // Ensure correctAnswer is an array
            if (typeof correctAnswerArray === 'string') {
                correctAnswerArray = [correctAnswerArray];
            } else if (!Array.isArray(correctAnswerArray)) {
                correctAnswerArray = correctAnswerArray ? [correctAnswerArray] : [];
            }

            const userAnswerSorted = (userAnswerArray || []).sort().join('');
            const correctAnswerSorted = correctAnswerArray.sort().join('');
            isCorrect = userAnswerSorted === correctAnswerSorted;
            displayCorrectAnswer = correctAnswerArray.join(', ');

        } else if (question.inputType === 'radio') {
            // Single selection
            isCorrect = userAnswer === question.correctAnswer;
            displayCorrectAnswer = question.correctAnswer;

        } else {
            // Unknown type - try to handle gracefully
            if (Array.isArray(userAnswer)) {
                const userAnswerSorted = userAnswer.sort().join('');
                const correct = Array.isArray(question.correctAnswer)
                    ? question.correctAnswer.sort().join('')
                    : question.correctAnswer;
                isCorrect = userAnswerSorted === correct;
                displayCorrectAnswer = correct;
            } else {
                isCorrect = userAnswer === question.correctAnswer;
                displayCorrectAnswer = question.correctAnswer;
            }
        }
    } catch (error) {
        console.error('Error in checkAnswer:', error);
        isCorrect = false;
    }

    window.answerStatus[questionId] = {
        isCorrect: isCorrect,
        correctAnswer: displayCorrectAnswer,
        userAnswer: userAnswer
    };

    // Re-render to show feedback
    renderQuestion();
}

// ===== Handle Answer Change =====
function handleAnswerChange(questionId, value, isMultiple) {
    if (isMultiple) {
        if (!userAnswers[questionId]) {
            userAnswers[questionId] = [];
        }

        const index = userAnswers[questionId].indexOf(value);
        if (index > -1) {
            userAnswers[questionId].splice(index, 1);
        } else {
            userAnswers[questionId].push(value);
        }

        // Sort to match answer format
        userAnswers[questionId].sort();
    } else {
        userAnswers[questionId] = value;
    }

    // Update UI
    const choices = document.querySelectorAll('.choice');
    choices.forEach(choice => {
        const input = choice.querySelector('input');
        if (input.checked) {
            choice.classList.add('selected');
        } else {
            choice.classList.remove('selected');
        }
    });
}

// ===== Navigation =====
function nextQuestion() {
    if (currentQuestionIndex < currentChapter.questions.length - 1) {
        currentQuestionIndex++;
        renderQuestion();
    }
}

function previousQuestion() {
    if (currentQuestionIndex > 0) {
        currentQuestionIndex--;
        renderQuestion();
    }
}

// ===== Exit Exam =====
function exitExam() {
    if (confirm('Are you sure you want to exit? Your progress will be lost.')) {
        if (timerInterval) clearInterval(timerInterval);
        showPage('mainPage');
    }
}

// ===== Submit Exam =====
function submitExam() {
    if (timerInterval) clearInterval(timerInterval);

    const totalTime = Date.now() - examStartTime;
    let correct = 0;
    let incorrect = 0;
    let scoreByChapter = {}; // Track scores by chapter for multi-chapter exams

    currentChapter.questions.forEach(question => {
        const userAnswer = userAnswers[question.id];
        let correctAnswer = question.correctAnswer;
        let isCorrect = false;

        try {
            if (question.inputType === 'checkbox') {
                // Handle multiple choice
                const userAnswerArray = userAnswer || [];
                let correctAnswerArray = correctAnswer;

                if (typeof correctAnswerArray === 'string') {
                    correctAnswerArray = [correctAnswerArray];
                } else if (!Array.isArray(correctAnswerArray)) {
                    correctAnswerArray = correctAnswerArray ? [correctAnswerArray] : [];
                }

                const userAnswerStr = (userAnswerArray || []).sort().join('');
                const correctAnswerStr = correctAnswerArray.sort().join('');
                isCorrect = userAnswerStr === correctAnswerStr;
            } else if (question.inputType === 'radio') {
                // Handle single choice
                isCorrect = userAnswer === correctAnswer;
            } else {
                // Fallback for unknown types
                if (Array.isArray(userAnswer)) {
                    const userStr = userAnswer.sort().join('');
                    const correct = Array.isArray(correctAnswer)
                        ? correctAnswer.sort().join('')
                        : correctAnswer;
                    isCorrect = userStr === correct;
                } else {
                    isCorrect = userAnswer === correctAnswer;
                }
            }
        } catch (error) {
            console.error('Error scoring question:', question.id, error);
            isCorrect = false;
        }

        if (isCorrect) {
            correct++;
        } else {
            incorrect++;
        }

        // Track scores by chapter for multi-chapter exams
        if (currentChapter.isMultiChapter && question.chapterId) {
            if (!scoreByChapter[question.chapterId]) {
                scoreByChapter[question.chapterId] = { correct: 0, total: 0 };
            }
            scoreByChapter[question.chapterId].total++;
            if (isCorrect) scoreByChapter[question.chapterId].correct++;
        }
    });

    const total = currentChapter.questions.length;
    const percentage = Math.round((correct / total) * 100);

    // Update results page
    document.getElementById('scorePercentage').textContent = `${percentage}%`;
    document.getElementById('correctCount').textContent = correct;
    document.getElementById('incorrectCount').textContent = incorrect;
    document.getElementById('totalCount').textContent = total;

    const minutes = Math.floor(totalTime / 60000);
    const seconds = Math.floor((totalTime % 60000) / 1000);
    document.getElementById('timeSpent').textContent =
        `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;

    // Add chapter breakdown for multi-chapter exams
    if (currentChapter.isMultiChapter && Object.keys(scoreByChapter).length > 0) {
        let chapterBreakdownHtml = '<div style="margin-top: 20px; padding: 15px; background: var(--bg-tertiary); border-radius: var(--radius); border-left: 4px solid var(--primary);"><h4 style="margin-top: 0; color: var(--primary-light);">Score by Chapter:</h4>';
        Object.entries(scoreByChapter).forEach(([chapterId, scores]) => {
            const chapterTitle = currentChapter.chapters.find(c => c.id === chapterId)?.title || chapterId;
            const chapterPercentage = Math.round((scores.correct / scores.total) * 100);
            chapterBreakdownHtml += `
                <div style="margin: 10px 0; padding: 8px; background: var(--bg-secondary); border-radius: 4px; display: flex; justify-content: space-between; align-items: center;">
                    <span>${chapterTitle}</span>
                    <strong style="color: ${chapterPercentage >= 80 ? 'var(--success)' : chapterPercentage >= 60 ? 'var(--warning)' : 'var(--danger)'};">${scores.correct}/${scores.total} (${chapterPercentage}%)</strong>
                </div>
            `;
        });
        chapterBreakdownHtml += '</div>';

        // Insert after results-stats
        const resultsStats = document.querySelector('.results-stats');
        if (resultsStats && resultsStats.parentElement) {
            const div = document.createElement('div');
            div.innerHTML = chapterBreakdownHtml;
            resultsStats.parentElement.insertBefore(div.firstChild, resultsStats.nextSibling);
        }
    }

    // Animate score ring
    const circumference = 2 * Math.PI * 90;
    const offset = circumference - (percentage / 100) * circumference;

    // Add SVG gradient
    const svg = document.querySelector('.score-ring');
    if (svg && !svg.querySelector('defs')) {
        const defs = document.createElementNS('http://www.w3.org/2000/svg', 'defs');
        const gradient = document.createElementNS('http://www.w3.org/2000/svg', 'linearGradient');
        gradient.setAttribute('id', 'scoreGradient');
        gradient.innerHTML = `
            <stop offset="0%" stop-color="hsl(250, 84%, 64%)" />
            <stop offset="100%" stop-color="hsl(199, 89%, 48%)" />
        `;
        defs.appendChild(gradient);
        svg.appendChild(defs);
    }

    setTimeout(() => {
        const scoreRing = document.getElementById('scoreRing');
        if (scoreRing) scoreRing.style.strokeDashoffset = offset;
    }, 300);

    // Update section status
    if (percentage >= 80) {
        currentSection.status = 'completed';
    } else {
        currentSection.status = 'in-progress';
    }
    updateFilterCounts();

    showPage('resultsPage');
}

// ===== Review Answers =====
function reviewAnswers() {
    currentQuestionIndex = 0;
    showPage('examPage');
    renderReviewQuestion();
}

function renderReviewQuestion() {
    const question = currentChapter.questions[currentQuestionIndex];
    const container = document.getElementById('questionContainer');

    const isMultipleChoice = question.inputType === 'checkbox';
    const userAnswer = userAnswers[question.id] || (isMultipleChoice ? [] : '');
    let correctAnswer = question.correctAnswer;

    // Ensure correctAnswer is properly formatted
    let correctAnswerArray = correctAnswer;
    if (typeof correctAnswerArray === 'string') {
        correctAnswerArray = [correctAnswerArray];
    } else if (!Array.isArray(correctAnswerArray)) {
        correctAnswerArray = correctAnswerArray ? [correctAnswerArray] : [];
    }

    let isCorrect = false;
    if (isMultipleChoice) {
        const userAnswerStr = (userAnswer || []).sort().join('');
        const correctAnswerStr = correctAnswerArray.sort().join('');
        isCorrect = userAnswerStr === correctAnswerStr;
    } else {
        isCorrect = userAnswer === correctAnswer;
    }

    // Build header with chapter tag for multi-chapter
    let headerHtml = `<div class="question-number">Question ${currentQuestionIndex + 1} of ${currentChapter.questions.length}`;
    if (currentChapter.isMultiChapter && question.chapterTitle) {
        headerHtml += ` <span style="background: #e3f2fd; color: #1976d2; padding: 2px 8px; border-radius: 4px; font-size: 12px; margin-left: 10px; font-weight: 500;">${question.chapterTitle}</span>`;
    }
    headerHtml += `</div>`;

    container.innerHTML = headerHtml + `
        <div class="question-text">${question.text}</div>
        <div class="choices">
            ${question.choices.map(choice => {
        const isUserChoice = isMultipleChoice
            ? userAnswer.includes(choice.value)
            : userAnswer === choice.value;

        const isCorrectChoice = correctAnswerArray.includes(choice.value);

        let choiceClass = '';
        if (isCorrectChoice) {
            choiceClass = 'correct';
        } else if (isUserChoice && !isCorrectChoice) {
            choiceClass = 'incorrect';
        }

        return `
                    <label class="choice ${choiceClass}" for="choice-${choice.value}">
                        <input 
                            type="${question.inputType}" 
                            id="choice-${choice.value}"
                            name="${question.inputName}" 
                            value="${choice.value}"
                            ${isUserChoice ? 'checked' : ''}
                            disabled
                        />
                        <span class="choice-label">
                            <strong>${choice.label}.</strong> ${choice.text}
                        </span>
                    </label>
                `;
    }).join('')}
        </div>
        <div style="margin-top: 2rem; padding: 1rem; background: var(--bg-tertiary); border-radius: var(--radius); border-left: 4px solid ${isCorrect ? 'var(--success)' : 'var(--danger)'};">
            <strong style="color: ${isCorrect ? 'var(--success)' : 'var(--danger)'};">
                ${isCorrect ? '✓ Correct' : '✗ Incorrect'}
            </strong>
        </div>
    `;

    // Highlight code blocks
    container.querySelectorAll('pre code').forEach((block) => {
        hljs.highlightElement(block);
    });

    // Update navigation
    document.getElementById('prevBtn').disabled = currentQuestionIndex === 0;
    document.getElementById('prevBtn').onclick = () => {
        if (currentQuestionIndex > 0) {
            currentQuestionIndex--;
            renderReviewQuestion();
        }
    };

    const isLastQuestion = currentQuestionIndex === currentChapter.questions.length - 1;
    document.getElementById('nextBtn').style.display = isLastQuestion ? 'none' : 'flex';
    document.getElementById('nextBtn').onclick = () => {
        if (currentQuestionIndex < currentChapter.questions.length - 1) {
            currentQuestionIndex++;
            renderReviewQuestion();
        }
    };

    document.getElementById('submitBtn').style.display = 'none';
}

// ===== Back to Home =====
function backToHome() {
    // Reset navigation functions
    document.getElementById('prevBtn').onclick = previousQuestion;
    document.getElementById('nextBtn').onclick = nextQuestion;

    showPage('mainPage');
    renderSections();
}
